# Generated by Django 3.1.1 on 2020-10-29 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('date', models.DateField(blank=True)),
                ('payment_option', models.CharField(max_length=50)),
                ('order_type', models.CharField(max_length=50)),
                ('order_status', models.CharField(max_length=50)),
                ('order_total', models.IntegerField()),
                ('no_of_people', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name_Def', models.CharField(db_column='dish', max_length=100)),
                ('category', models.CharField(db_column='category', max_length=100)),
                ('subcategory', models.CharField(db_column='subcategory', max_length=100)),
                ('active', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='RoomTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('room_tables', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('room_n', models.CharField(default='a', editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_room', models.CharField(max_length=200)),
                ('table_no', models.SmallIntegerField()),
                ('table_n', models.CharField(blank=True, max_length=200, null=True)),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('is_close', models.BooleanField(default=0)),
                ('cust_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CustomerAndDish.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(default=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CustomerAndDish.defaultdish'), max_length=50)),
                ('category', models.CharField(default='--', max_length=50)),
                ('subcategory', models.CharField(default='--', max_length=50)),
                ('active', models.CharField(default='Available', max_length=50)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('price', models.IntegerField()),
                ('def_dish_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CustomerAndDish.defaultdish')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dish_price', models.IntegerField()),
                ('dish_row_total', models.IntegerField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerAndDish.customer')),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerAndDish.dish')),
            ],
            options={
                'unique_together': {('cust_id', 'dish_id')},
            },
        ),
    ]
