# Generated by Django 3.1.1 on 2020-11-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAndDish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='table',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Table No.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='time_in',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
