# Generated by Django 3.1.1 on 2020-11-02 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAndDish', '0002_auto_20201102_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order_total',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='cust_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomerAndDish.customer'),
        ),
    ]
