# Generated by Django 3.1.1 on 2020-11-02 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAndDish', '0004_auto_20201102_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableinfo',
            name='cust_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='CustomerAndDish.customer'),
        ),
    ]
