# Generated by Django 3.1.1 on 2020-11-02 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAndDish', '0005_auto_20201102_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableinfo',
            name='cust_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CustomerAndDish.customer'),
        ),
    ]
