# Generated by Django 3.1.1 on 2020-11-02 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAndDish', '0006_auto_20201102_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableinfo',
            name='cust_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomerAndDish.customer'),
        ),
    ]
