# Generated by Django 3.1.1 on 2020-11-03 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAndDish', '0007_auto_20201102_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='active',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='cust_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomerAndDish.customer'),
        ),
    ]
