# Generated by Django 3.1.1 on 2020-11-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAndDish', '0008_auto_20201103_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='time_in',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
