# Generated by Django 3.1.1 on 2020-11-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAndDish', '0009_auto_20201104_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableinfo',
            name='in_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
