# Generated by Django 3.1.1 on 2020-11-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAndDish', '0011_auto_20201104_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='time_in',
            field=models.TimeField(blank=True),
        ),
    ]
