# Generated by Django 3.1.1 on 2020-11-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAndDish', '0012_auto_20201112_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableinfo',
            name='in_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
